In [7]:
import numpy as np
import pandas as pd
bnk=pd.read_html('https://www.fdic.gov/bank-failures/failed-bank-list')

In [8]:
bnk

[                                            Bank Name               City  \
 0                                 Small Business Bank             Lenexa
 1       Kentland Federal Savings and Loan Association           Kentland
 2             Community Bank and Trust - West Georgia           LaGrange
 3                   Metropolitan Capital Bank & Trust            Chicago
 4                        The Santa Anna National Bank         Santa Anna
 5                                Pulaski Savings Bank            Chicago
 6                  The First National Bank of Lindsay            Lindsay
 7               Republic First Bank dba Republic Bank       Philadelphia
 8                                       Citizens Bank           Sac City
 9                            Heartland Tri-State Bank            Elkhart
 10                                First Republic Bank      San Francisco
 11                                     Signature Bank           New York
 12                                Silicon Valley Bank        Santa Clara
 13                                  Almena State Bank             Almena
 14                         First City Bank of Florida  Fort Walton Beach
 15                               The First State Bank      Barboursville
 16                                 Ericson State Bank            Ericson
 17                   City National Bank of New Jersey             Newark
 18                                      Resolute Bank             Maumee
 19                              Louisa Community Bank             Louisa
 20                               The Enloe State Bank             Cooper
 21                Washington Federal Bank for Savings            Chicago
 22    The Farmers and Merchants State Bank of Argonia            Argonia
 23                                Fayette County Bank         Saint Elmo
 24  Guaranty Bank, (d/b/a BestBank in Georgia & Mi...          Milwaukee

             State   Cert                     Acquiring Institution  \
 0          Kansas  25744  The Farmers State Bank of Oakley, Kansas
 1         Indiana  28722                             Kentland Bank
 2         Georgia  25796                               Anchor Bank
 3        Illinois  57488                   First Independence Bank
 4           Texas   5520                 Coleman County State Bank
 5        Illinois  28611                           Millennium Bank
 6        Oklahoma   4134                    First Bank & Trust Co.
 7    Pennsylvania  27332         Fulton Bank, National Association
 8            Iowa   8758                 Iowa Trust & Savings Bank
 9          Kansas  25851                    Dream First Bank, N.A.
 10     California  59017                 JPMorgan Chase Bank, N.A.
 11       New York  57053                       Flagstar Bank, N.A.
 12     California  24735       First–Citizens Bank & Trust Company
 13         Kansas  15426                               Equity Bank
 14        Florida  16748                 United Fidelity Bank, fsb
 15  West Virginia  14361                            MVB Bank, Inc.
 16       Nebraska  18265                Farmers and Merchants Bank
 17     New Jersey  21111                           Industrial Bank
 18           Ohio  58317                        Buckeye State Bank
 19       Kentucky  58112         Kentucky Farmers Bank Corporation
 20          Texas  10716                        Legend Bank, N. A.
 21       Illinois  30570                        Royal Savings Bank
 22         Kansas  17719                               Conway Bank
 23       Illinois   1802                 United Fidelity Bank, fsb
 24      Wisconsin  30003       First-Citizens Bank & Trust Company

          Closing Date  Fund  Sort ascending
 0       July 17, 2026                 10553
 1       July 10, 2026                 10552
 2         May 1, 2026                 10551
 3    January 30, 2026                 10550
 4       June 27, 2025                 10549
 5    January 17, 2025                 10548
 6    October 18, 2024                 10547
 7      April 26, 2024                 10546
 8    November 3, 2023                 10545
 9       July 28, 2023                 10544
 10        May 1, 2023                 10543
 11     March 12, 2023                 10540
 12     March 10, 2023                 10539
 13   October 23, 2020                 10538
 14   October 16, 2020                 10537
 15      April 3, 2020                 10536
 16  February 14, 2020                 10535
 17   November 1, 2019                 10534
 18   October 25, 2019                 10533
 19   October 25, 2019                 10532
 20       May 31, 2019                 10531
 21  December 15, 2017                 10530
 22   October 13, 2017                 10529
 23       May 26, 2017                 10528
 24        May 5, 2017                 10527  ]

In [9]:
bnk=bnk[0]
bnk

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Small Business Bank,Lenexa,Kansas,25744,"The Farmers State Bank of Oakley, Kansas","July 17, 2026",10553
1,Kentland Federal Savings and Loan Association,Kentland,Indiana,28722,Kentland Bank,"July 10, 2026",10552
2,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
3,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
4,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
5,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
6,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
7,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
8,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
9,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
10,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
11,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
12,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
13,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
14,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
15,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
16,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
17,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
18,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
19,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
20,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
21,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
22,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
23,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
24,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527

In [10]:
bnk.dtypes

Bank Name                object
City                     object
State                    object
Cert                      int64
Acquiring Institution    object
Closing Date             object
Fund  Sort ascending      int64
dtype: object

In [13]:
bnk.columns=(bnk.columns.str.lower().str.replace(' ',"_"))
bnk.columns

Index(['bank_name', 'city', 'state', 'cert', 'acquiring_institution',
       'closing_date', 'fund__sort_ascending'],
      dtype='object')

In [14]:
bnk['closing_date']=pd.to_datetime(bnk['closing_date'])
bnk['closing_date'].head(10)

0   2026-07-17
1   2026-07-10
2   2026-05-01
3   2026-01-30
4   2025-06-27
5   2025-01-17
6   2024-10-18
7   2024-04-26
8   2023-11-03
9   2023-07-28
Name: closing_date, dtype: datetime64[ns]

In [15]:
bnk.isna().sum()

bank_name                0
city                     0
state                    0
cert                     0
acquiring_institution    0
closing_date             0
fund__sort_ascending     0
dtype: int64

In [16]:
total_failed=len(bnk)
total_failed

25

In [17]:
bnk['closing_date'].min()

Timestamp('2017-05-05 00:00:00')

In [18]:
bnk['closing_date'].max()

Timestamp('2026-07-17 00:00:00')

In [20]:
state_counts=bnk['state'].value_counts()
state_counts

state
Kansas           4
Illinois         4
Texas            2
California       2
Georgia          1
Oklahoma         1
Pennsylvania     1
Iowa             1
Indiana          1
New York         1
Florida          1
West Virginia    1
Nebraska         1
New Jersey       1
Ohio             1
Kentucky         1
Wisconsin        1
Name: count, dtype: int64

In [23]:
state_counts.head(5)

state
Kansas        4
Illinois      4
Texas         2
California    2
Georgia       1
Name: count, dtype: int64

In [24]:
bnk['year']=bnk['closing_date'].dt.year
bnk['year'].head()

0    2026
1    2026
2    2026
3    2026
4    2025
Name: year, dtype: int32

In [25]:
failures_per_year=bnk.groupby('year').size()
failures_per_year

year
2017    4
2019    4
2020    4
2023    5
2024    2
2025    2
2026    4
dtype: int64

In [26]:
bnk['year'].min()

2017

In [27]:
failures_per_year.idxmax(),failures_per_year.max()

(np.int32(2023), 5)

In [28]:
failures_per_year.idxmin(),failures_per_year.min()

(np.int32(2024), 2)

In [29]:
min_val=failures_per_year.min()
failures_per_year[failures_per_year== min_val]

year
2024    2
2025    2
dtype: int64

In [30]:
state_year_pivot=pd.pivot_table(
    bnk,
    values='bank_name',
    index='year',
    columns='state',
    aggfunc='count'
)
state_year_pivot.head()

state,California,Florida,Georgia,Illinois,Indiana,Iowa,Kansas,Kentucky,Nebraska,New Jersey,New York,Ohio,Oklahoma,Pennsylvania,Texas,West Virginia,Wisconsin
year,,,,,,,,,,,,,,,,,
2017,NaN,NaN,NaN,2.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,1.0,NaN,NaN,1.0,NaN,NaN
2020,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
2023,2.0,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN

In [31]:
state_year_pivot.isna().sum()

state
California       6
Florida          6
Georgia          6
Illinois         4
Indiana          6
Iowa             6
Kansas           3
Kentucky         6
Nebraska         6
New Jersey       6
New York         6
Ohio             6
Oklahoma         6
Pennsylvania     6
Texas            5
West Virginia    6
Wisconsin        6
dtype: int64

In [37]:
bnk['acquiring_institution'].nunique()

24

In [39]:
bnk['acquiring_institution'].value_counts()

acquiring_institution
United Fidelity Bank, fsb                   2
The Farmers State Bank of Oakley, Kansas    1
Kentland Bank                               1
Conway Bank                                 1
Royal Savings Bank                          1
Legend Bank, N. A.                          1
Kentucky Farmers Bank Corporation           1
Buckeye State Bank                          1
Industrial Bank                             1
Farmers and Merchants Bank                  1
MVB Bank, Inc.                              1
Equity Bank                                 1
First–Citizens Bank & Trust Company         1
Flagstar Bank, N.A.                         1
JPMorgan Chase Bank, N.A.                   1
Dream First Bank, N.A.                      1
Iowa Trust & Savings Bank                   1
Fulton Bank, National Association           1
First Bank & Trust Co.                      1
Millennium Bank                             1
Coleman County State Bank                   1
First Independence Bank                     1
Anchor Bank                                 1
First-Citizens Bank & Trust Company         1
Name: count, dtype: int64

In [40]:
top_acquires=bnk['acquiring_institution'].value_counts().head(5)

In [43]:
top_acquires

acquiring_institution
United Fidelity Bank, fsb                   2
The Farmers State Bank of Oakley, Kansas    1
Kentland Bank                               1
Conway Bank                                 1
Royal Savings Bank                          1
Name: count, dtype: int64

In [44]:
bnk.groupby('acquiring_institution').size()

acquiring_institution
Anchor Bank                                 1
Buckeye State Bank                          1
Coleman County State Bank                   1
Conway Bank                                 1
Dream First Bank, N.A.                      1
Equity Bank                                 1
Farmers and Merchants Bank                  1
First Bank & Trust Co.                      1
First Independence Bank                     1
First-Citizens Bank & Trust Company         1
First–Citizens Bank & Trust Company         1
Flagstar Bank, N.A.                         1
Fulton Bank, National Association           1
Industrial Bank                             1
Iowa Trust & Savings Bank                   1
JPMorgan Chase Bank, N.A.                   1
Kentland Bank                               1
Kentucky Farmers Bank Corporation           1
Legend Bank, N. A.                          1
MVB Bank, Inc.                              1
Millennium Bank                             1
Royal Savings Bank                          1
The Farmers State Bank of Oakley, Kansas    1
United Fidelity Bank, fsb                   2
dtype: int64

In [45]:
failures_per_year.mean()

np.float64(3.5714285714285716)

In [47]:
rolling_avg=failures_per_year.rolling(3).mean()
rolling_avg

year
2017         NaN
2019         NaN
2020    4.000000
2023    4.333333
2024    3.666667
2025    3.000000
2026    2.666667
dtype: float64